name: Bug Report
description: Create a report to help us improve Cosignal
title: '[BUG] '
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run '...'
        2. Call '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: input
    id: version
    attributes:
      label: Environment & Version
      placeholder: Python 3.11, macOS, Cosignal v0.1.0
